use_frameworks!

platform :ios, '11.0'

target 'FlaneurImagePicker_Example' do
  pod 'FlaneurImagePicker', :path => '../'

  target 'FlaneurImagePicker_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
